version: '3.8'

services:
  notasapp:
    image: camiloarroyo/notas-app:v1.0
    deploy:
      replicas: 3
    ports:
      - "4201:80"   
  apinotascont:
    image: camiloarroyo/api-notas:v1.0
    deploy:
      replicas: 2
    ports:
      - "8081:8080"  
